In [2]:
#Import Carseats from csv file
import pandas as pd
import numpy as np
carseats = pd.read_csv("Carseats.csv", header=0)
del carseats['Unnamed: 0']
carseats.head(10)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No
5,10.81,124,113,13,501,72,Bad,78,16,No,Yes
6,6.63,115,105,0,45,108,Medium,71,15,Yes,No
7,11.85,136,81,15,425,120,Good,67,10,Yes,Yes
8,6.54,132,110,0,108,124,Medium,76,10,No,No
9,4.69,132,113,0,131,124,Medium,76,17,No,Yes

In [3]:
#Transform Sales into a binary factor called High
carseats['High'] = (carseats.Sales > 8).astype(bool)
carseats.head(10)

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US,High
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes,True
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes,True
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes,True
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes,False
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No,False
5,10.81,124,113,13,501,72,Bad,78,16,No,Yes,True
6,6.63,115,105,0,45,108,Medium,71,15,Yes,No,False
7,11.85,136,81,15,425,120,Good,67,10,Yes,Yes,True
8,6.54,132,110,0,108,124,Medium,76,10,No,No,False
9,4.69,132,113,0,131,124,Medium,76,17,No,Yes,False

In [4]:
carseats['Urban'] = (carseats.Urban == "Yes").astype(int)
carseats['US'] = (carseats.US == "Yes").astype(int)
carseats['ShelveLoc_'] = 0
carseats['ShelveLoc_'][carseats['ShelveLoc'] =="Good"] = 1
carseats['ShelveLoc_'][carseats['ShelveLoc'] =="Medium"] = 2
carseats['ShelveLoc_'][carseats['ShelveLoc'] =="Bad"] = 3
carseats.head(10)

C:\Users\sri-dell\Anaconda2\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\sri-dell\Anaconda2\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\sri-dell\Anaconda2\lib\site-packages\ipykernel\__main__.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US,High,ShelveLoc_
0,9.50,138,73,11,276,120,Bad,42,17,1,1,True,3
1,11.22,111,48,16,260,83,Good,65,10,1,1,True,1
2,10.06,113,35,10,269,80,Medium,59,12,1,1,True,2
3,7.40,117,100,4,466,97,Medium,55,14,1,1,False,2
4,4.15,141,64,3,340,128,Bad,38,13,1,0,False,3
5,10.81,124,113,13,501,72,Bad,78,16,0,1,True,3
6,6.63,115,105,0,45,108,Medium,71,15,1,0,False,2
7,11.85,136,81,15,425,120,Good,67,10,1,1,True,1
8,6.54,132,110,0,108,124,Medium,76,10,0,0,False,2
9,4.69,132,113,0,131,124,Medium,76,17,0,1,False,2

In [5]:
#Select response y and training set X
y = carseats['High']
cols_to_keep = ['CompPrice', 'Income', 'Advertising', 'Population', 'Price', 'ShelveLoc_', 
                'Age','Education', 'Urban']
X = carseats[cols_to_keep]

In [6]:
from sklearn import tree
cltree = tree.DecisionTreeClassifier()
cltree = cltree.fit(X, y)

In [7]:
#Evaluate the model
from sklearn.cross_validation import cross_val_score
scores = cross_val_score(cltree, X, y, cv=10)
print scores.mean()

0.715234521576

In [8]:
#Export the tree in Graphviz format using the export_graphviz
dotfile = open("tree.dot", 'w')
tree.export_graphviz(cltree, out_file = dotfile, feature_names = X.columns)
dotfile.close()